apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - name: udacity-capstone
        image: seewei/udacity-capstone
        ports:
        - containerPort: 80

---      
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
