version: 2.1
jobs:
  lint:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
  
      # Download and cache dependencies
    #   - restore_cache:
    #       keys:
    #         # fallback to using the latest cache if no exact match is found
    #         - v1-dependencies
  
      - run:
          name: install dependencies
          command: |
            make install
            # Install hadolint
            # wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            # chmod +x /bin/hadolint
  
       # run lint!
      - run:
          name: run lint
          command: |
            make lint   

workflows:
  default:
    jobs:
        - lint