version: 2.1
jobs:
  lint:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
  
      - run:
          name: install dependencies
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
  
       # run lint!
      - run:
          name: run lint
          command: |
            make lint   
            
  docker-build-push:
    docker:
      - image: docker:17.05.0-ce-git
      
    steps:
      - checkout
      
      - run:
        name: build and push docker
        command: |
          chmod +x docker_run_push.sh
          ./docker_run_push.sh
          
    

workflows:
  default:
    jobs:
      - lint
      - docker-build-push:
          requires: [lint]